<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TablaCodigo; 



class TablaCodigosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $tablas = [                        
            ['codigo'=>'1'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'TITULO DE PROPIEDAD'],
            ['codigo'=>'2'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONTRATO DE COMPRA-VENTA'],
            ['codigo'=>'5'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONTRATO DE PRESTAMO CON INSTITUCIONES'],
            ['codigo'=>'11'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PARTIDA DE DEFUNCION'],
            ['codigo'=>'5'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'INVITADO'],
            ['codigo'=>'5'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'CONTROL CALIDAD DISTRITAL'],
            ['codigo'=>'7'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'PROGRAMACION GENERAL'],
            ['codigo'=>'8'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'SUPERVISION'],
            ['codigo'=>'9'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'PROGRAMACION POR AREA'],
            ['codigo'=>'1'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'GESTION CONVENIOS'],
            ['codigo'=>'2'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'ELABORACION MOSAICO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'LEVANTAMIENTO TOPOGRAFICO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'LEVANTAMIENTO CATASTRAL'],
            ['codigo'=>'10'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'EDICION GRAFICA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'ARE'	,'desc_codigo'=>'DIGITACION FICHAS CATASTRALES'],
            ['codigo'=>'9'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'PUESTO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'STAND'],
            ['codigo'=>'9'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'DNI'],
            ['codigo'=>'13'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PARTIDA DE MATRIMONIO'],
            ['codigo'=>'14'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'DOC. DE TRANFERENCIA'],
            ['codigo'=>'15'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PODERES'],
            ['codigo'=>'1'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL OMISO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL SUBVALUADO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL SOBREVALUADO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'EPC'	,'desc_codigo'=>'PREDIO CATASTRAL CONFORME'],
            ['codigo'=>'11'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO VARIABLE'],
            ['codigo'=>'12'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO LUMINOSO'],
            ['codigo'=>'13'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO DE PROYECCION'],
            ['codigo'=>'14'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ECOLOGICO ILUMINADO'],
            ['codigo'=>'21'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL VARIABLE'],
            ['codigo'=>'22'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL LUMINOSO'],
            ['codigo'=>'23'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL DE PROYECCION'],
            ['codigo'=>'24'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTEL ILUMINADO'],
            ['codigo'=>'31'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA VARIABLE'],
            ['codigo'=>'32'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA LUMINOSO'],
            ['codigo'=>'33'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA DE PROYECCION'],
            ['codigo'=>'34'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'CARTELERA ILUMINADO'],
            ['codigo'=>'41'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO VARIABLE'],
            ['codigo'=>'42'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO LUMINOSO'],
            ['codigo'=>'43'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO DE PROYECCION'],
            ['codigo'=>'44'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'GLOBO AEROSTATICO ILUMINADO'],
            ['codigo'=>'51'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO VARIABLE'],
            ['codigo'=>'52'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO LUMINOSO'],
            ['codigo'=>'53'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO DE PROYECCION'],
            ['codigo'=>'54'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRERO ILUMINADO'],
            ['codigo'=>'61'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS VARIABLE'],
            ['codigo'=>'62'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS LUMINOSO'],
            ['codigo'=>'63'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS DE PROYECCION'],
            ['codigo'=>'64'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'LETRAS RECORTADAS ILUMINADO'],
            ['codigo'=>'71'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA VARIABLE'],
            ['codigo'=>'72'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA LUMINOSO'],
            ['codigo'=>'73'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA DE PROYECCION'],
            ['codigo'=>'74'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'MARQUESINA ILUMINADO'],
            ['codigo'=>'81'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE VARIABLE'],
            ['codigo'=>'82'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE LUMINOSO'],
            ['codigo'=>'83'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE DE PROYECCION'],
            ['codigo'=>'84'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL SIMPLE ILUMINADO'],
            ['codigo'=>'91'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL VARIABLE'],
            ['codigo'=>'92'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL LUMINOSO'],
            ['codigo'=>'93'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL DE PROYECCION'],
            ['codigo'=>'94'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PANEL MONUMENTAL ILUMINADO'],
            ['codigo'=>'101'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES VARIABLE'],
            ['codigo'=>'102'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES LUMINOSO'],
            ['codigo'=>'103'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES DE PROYECCION'],
            ['codigo'=>'104'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'PROYECCIONES ILUMINADO'],
            ['codigo'=>'111'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS VARIABLE'],
            ['codigo'=>'112'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS LUMINOSO'],
            ['codigo'=>'113'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS DE PROYECCION'],
            ['codigo'=>'114'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'ROTULOS EN VEHICULOS ILUMINADO'],
            ['codigo'=>'121'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS VARIABLE'],
            ['codigo'=>'122'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS LUMINOSO'],
            ['codigo'=>'123'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS DE PROYECCION'],
            ['codigo'=>'124'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'TOLDOS ILUMINADO'],
            ['codigo'=>'131'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO VARIABLE'],
            ['codigo'=>'132'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO LUMINOSO'],
            ['codigo'=>'133'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO DE PROYECCION'],
            ['codigo'=>'134'	    ,'id_tabla'=>'ANU'	,'desc_codigo'=>'AVISO ESCULTORIO ILUMINADO'],
            ['codigo'=>'14'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'17'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'PENSIONISTA'],
            ['codigo'=>'AA.HH.','id_tabla'=>'HUR','desc_codigo'=>'ASENTAMIENTO HUMANO '],
            ['codigo'=>'AA.HH. MRG','id_tabla'=>'HUR','desc_codigo'=>'ASENTAMIENTO HUMANO MARGINAL'],
            ['codigo'=>'ADV.','id_tabla'=>'HUR','desc_codigo'=>'ASOCIACION DE VIVIENDA'],
            ['codigo'=>'APV.','id_tabla'=>'HUR','desc_codigo'=>'ASOCIACION PRO VIVIENDA'],
            ['codigo'=>'ASOC.','id_tabla'=>'HUR','desc_codigo'=>'ASOCIACION'],
            ['codigo'=>'ASOC. RES.','id_tabla'=>'HUR','desc_codigo'=>'ASOCIACION RESIDENCIAL'],
            ['codigo'=>'CC. HH. ','id_tabla'=>'HUR','desc_codigo'=>'CONJUNTO HABITACIONAL '],
            ['codigo'=>'COOP. VIV.','id_tabla'=>'HUR','desc_codigo'=>'COOPERATIVA DE VIVIENDA'],
            ['codigo'=>'JUNT. PROP','id_tabla'=>'HUR','desc_codigo'=>'JUNTA DE PROPIETARIOS'],
            ['codigo'=>'JUNT. COMP','id_tabla'=>'HUR','desc_codigo'=>'JUNTA DE COMPRADORES'],
            ['codigo'=>'PP.JJ.','id_tabla'=>'HUR','desc_codigo'=>'PUEBLO JOVEN'],
            ['codigo'=>'PREDIO','id_tabla'=>'HUR','desc_codigo'=>'PREDIO'],
            ['codigo'=>'PRG. VIV.','id_tabla'=>'HUR','desc_codigo'=>'PROGRAMA DE VIVIENDA '],
            ['codigo'=>'QUINTA PRV','id_tabla'=>'HUR','desc_codigo'=>'QUINTA PRIVADA '],
            ['codigo'=>'SUBDIVISIO','id_tabla'=>'HUR','desc_codigo'=>'SUBDIVISION DE PREDIO URBANO'],
            ['codigo'=>'URB.','id_tabla'=>'HUR','desc_codigo'=>'URBANIZACIÓN'],
            ['codigo'=>'URB. POP.','id_tabla'=>'HUR','desc_codigo'=>'URBANIZACIÓN POPULAR'],
            ['codigo'=>'S/T.','id_tabla'=>'HUR','desc_codigo'=>'SIN TIPO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'DFB'	,'desc_codigo'=>'FABRICA INSCRITA'],
            ['codigo'=>'2'	    ,'id_tabla'=>'DFB'	,'desc_codigo'=>'FABRICA NO INSCRITA'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'TITULAR CATASTRAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'ARRENDATARIO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'CESION EN USO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'TITULAR CATASTRAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'REPRESENTANTE LEGAL'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'ARRENDATARIO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'FAMILIAR'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CASA HABITACION'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TIENDA / DEPOSITO / ALMACEN'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'PREDIO EN EDIFICIO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'41'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CLINICA'],
            ['codigo'=>'410'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CEMENTERIO'],
            ['codigo'=>'411'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'SUB ESTACION'],
            ['codigo'=>'412'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'BANCO FINANCIERA'],
            ['codigo'=>'413'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TERMINAL DE TRANSPORTE'],
            ['codigo'=>'414'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'MERCADO'],
            ['codigo'=>'415'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CLUB SOCIAL'],
            ['codigo'=>'416'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CLUB DE ESPARCIMIENTO'],
            ['codigo'=>'417'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'PLAYA DE ESTACIONAMIENTO'],
            ['codigo'=>'42'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'HOSPITAL'],
            ['codigo'=>'43'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CINE / TEATRO'],
            ['codigo'=>'6'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'13'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'POSESIÓN'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CDE'	,'desc_codigo'=>'VECINO'],
            ['codigo'=>'44'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'INDUSTRIA'],
            ['codigo'=>'45'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TALLER'],
            ['codigo'=>'46'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'IGLESIA / TEMPLO'],
            ['codigo'=>'47'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'CENTRO DE ENSEÑANZA'],
            ['codigo'=>'48'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'SERVICIO DE COMIDA'],
            ['codigo'=>'49'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'PARQUE'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'TERRENO SIN CONSTRUIR'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CEP'	,'desc_codigo'=>'MONUMENTO HISTORICO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CEP'	,'desc_codigo'=>'PREDIO RUSTICO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CEP'	,'desc_codigo'=>'SISTEMA DE AYUDA DE AERONAVEGACION'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO CENTRAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO LOCAL'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO REGIONAL'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'BENEFICENCIA PUBLICA'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'HOSPITALES'],
            ['codigo'=>'6'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ENTIDADES RELIGIOSAS'],
            ['codigo'=>'7'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'CUERPO GENERAL DE BOMBEROS'],
            ['codigo'=>'8'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'UNIVERSIDADES'],
            ['codigo'=>'9'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'CENTRO EDUCATIVO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'COMUNIDAD CAMPESINA / NATIVA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANISMOS INTERNACIONALES'],
            ['codigo'=>'12'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'GOBIERNO EXTRANJERO'],
            ['codigo'=>'13'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANIZACION POLITICA'],
            ['codigo'=>'14'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'PATRIMONIO CULTURAL DE LA NACION'],
            ['codigo'=>'15'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANIZACIONES SINDICALES'],
            ['codigo'=>'16'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'ORGANIZACIONES DE DISCAPACITADOS'],
            ['codigo'=>'17'	    ,'id_tabla'=>'CET'	,'desc_codigo'=>'PENSIONISTA'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'GENERADO POR MUNICIPALIDAD'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'AUTOGENERADO POR EL TITULAR CAT.'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'GENERADO POR EL TÉCNICO CAT.'],
            ['codigo'=>'1'	    ,'id_tabla'=>'DFE'	,'desc_codigo'=>'LICENCIA DE FUNCIONAMIENTO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'DFE'	,'desc_codigo'=>'LICENCIA DE ANUNCIOS'],
            ['codigo'=>'3'	    ,'id_tabla'=>'DFE'	,'desc_codigo'=>'LICENCIA DE FUNCIONAMIENTO Y ANUNCIOS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'NO PRESENTO DOCUMENTO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'DNI'],
            ['codigo'=>'3'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'CARNET DE IDENTIDAD DE POLICIA NACIONAL'],
            ['codigo'=>'4'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'CARNET DE IDENTIDAD DE FUERZAS ARMADAS'],
            ['codigo'=>'5'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'PARTIDA DE NACIMIENTO'],
            ['codigo'=>'6'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'PASAPORTE'],
            ['codigo'=>'7'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'CARNET DE EXTRANJERIA'],
            ['codigo'=>'1'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'TERMINADO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'EN CONSTRUCCION'],
            ['codigo'=>'3'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'INCONCLUSA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'ECC'	,'desc_codigo'=>'EN RUINAS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'MUY BUENO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'BUENO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'REGULAR'],
            ['codigo'=>'4'	    ,'id_tabla'=>'ECS'	,'desc_codigo'=>'MALO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'SOLTERO(A)'],
            ['codigo'=>'2'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'CASADO(A)'],
            ['codigo'=>'3'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'DIVORCIADO(A)'],
            ['codigo'=>'4'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'VIUDO(A)'],
            ['codigo'=>'5'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'CONVIVIENTE'],
            ['codigo'=>'1'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'COMPRA VENTA'],
            ['codigo'=>'2'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'ANTICIPO LEGITIMA'],
            ['codigo'=>'3'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'TESTAMENTO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'DONACION'],
            ['codigo'=>'5'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'ADJUDICACION'],
            ['codigo'=>'6'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'FUSION'],
            ['codigo'=>'7'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'EXPROPIACION'],
            ['codigo'=>'8'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'PERMUTA'],
            ['codigo'=>'9'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'PRESCRIPCION ADQUISITIVA'],
            ['codigo'=>'10'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'CESION DE DERECHOS DE ACCIONES'],
            ['codigo'=>'11'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'DACION EN PAGO'],
            ['codigo'=>'12'	    ,'id_tabla'=>'FAQ'	,'desc_codigo'=>'DECLARACION DE HEREDEROS'],
            ['codigo'=>'1'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'FICHA COMPLETA'],
            ['codigo'=>'2'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'FICHA INCOMPLETA'],
            ['codigo'=>'3'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'COMPLETADA EN OFICINA'],
            ['codigo'=>'4'	        ,'id_tabla'=>'LLE'	,'desc_codigo'=>'COMPLETADA EN CONTROL EXTERIOR'],
            ['codigo'=>'1'	        ,'id_tabla'=>'LOG'	,'desc_codigo'=>'SI'],
            ['codigo'=>'2'	        ,'id_tabla'=>'LOG'	,'desc_codigo'=>'NO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'CONCRETO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'LADRILLO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'ADOBE(QUINCHA'],
            ['codigo'=>'1'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR VARIACION DE UNIDADES'],
            ['codigo'=>'2'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR VARIACION EN LA CONSTRUCCION'],
            ['codigo'=>'3'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR VARIACION DE PORCENTAJE'],
            ['codigo'=>'4'	        ,'id_tabla'=>'MFC'	,'desc_codigo'=>'POR CAMBIO DE USO'],
            ['codigo'=>'1'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR SER PREDIO CATASTRAL NUEVO'],
            ['codigo'=>'2'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR TENER VARIACION EN AREA DE USO'],
            ['codigo'=>'3'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR CAMBIO DE CONDUCTOR'],
            ['codigo'=>'4'	        ,'id_tabla'=>'MFE'	,'desc_codigo'=>'POR CAMBIO DE GIRO'],
            ['codigo'=>'1'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR SER PREDIO CATASTRAL NUEVO'],
            ['codigo'=>'2'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR VARIACION EN LA CONSTRUCCION'],
            ['codigo'=>'3'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR CAMBIO DEL TITULAR CATASTRAL'],
            ['codigo'=>'4'	        ,'id_tabla'=>'MFI'	,'desc_codigo'=>'POR CAMBIO DE USO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'GALERIA'],
            ['codigo'=>'2'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'MERCADO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CAMPO FERIAL'],
            ['codigo'=>'4'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CENTRO COMERCIAL'],
            ['codigo'=>'5'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'QUINTA'],
            ['codigo'=>'6'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CALLEJON'],
            ['codigo'=>'7'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'PREDIO INDEPENDIENTE'],
            ['codigo'=>'8'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'SOLAR'],
            ['codigo'=>'9'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'CORRALON'],
            ['codigo'=>'10'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'AZOTEA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'AIRES'],
            ['codigo'=>'12'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'PREDIO EN EDIFICIO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'CONFORMIDAD DE OBRA'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'LICENCIA DE CONSTRUCCION'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'DECLARATORIA DE FÁBRICA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'ULTIMA DECLARACION JURADA AUTOAVALUO'],
            ['codigo'=>'5'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'RESOLUCION DE EXONERACION'],
            ['codigo'=>'6'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'PODERES'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'BLOCK'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'CASA / CHALET'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'EDIFICIO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TED'	,'desc_codigo'=>'PABELLON'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'DEPARTAMENTO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'CASA / CHALET'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'OFICINA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'ESTACIONAMIENTO'],
            ['codigo'=>'5'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'DEPOSITO'],
            ['codigo'=>'6'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'TENDAL'],
            ['codigo'=>'7'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'TIENDA'],
            ['codigo'=>'8'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'PUESTO'],
            ['codigo'=>'9'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'STAND'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'TOMO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'FICHA'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'PARTIDA ELECTRONICA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TPA'	,'desc_codigo'=>'CÓDIGO DE PREDIO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'EMPRESA'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'COOPERATIVA'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'ASOCIACION'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'FUNDACION'],
            ['codigo'=>'E'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'ESTACIONAMIENTO'],
            ['codigo'=>'G'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'GARAGE'],
            ['codigo'=>'P'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'PRINCIPAL'],
            ['codigo'=>'S'	        ,'id_tabla'=>'TPR'	,'desc_codigo'=>'SECUNDARIO'],
            ['codigo'=>'1'	        ,'id_tabla'=>'TPE'	,'desc_codigo'=>'PERSONA NATURAL'],
            ['codigo'=>'2'	        ,'id_tabla'=>'TPE'	,'desc_codigo'=>'PERSONA JURIDICA'],
            ['codigo'=>'1'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN RETIRO MUNICIPAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN JARDÍN DE AISLAMIENTO'],
            ['codigo'=>'3'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN VIA PUBLICA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN LOTE COLINDANTE'],
            ['codigo'=>'5'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'ALTURA NO REGLAMENTARIA'],
            ['codigo'=>'6'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN PARQUE'],
            ['codigo'=>'AL'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'ALAMEDA'],
            ['codigo'=>'AV'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'AVENIDA'],
            ['codigo'=>'CA'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'CALLE'],
            ['codigo'=>'CAM'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'CAMINO'],
            ['codigo'=>'CTRA'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'CARRETERA'],
            ['codigo'=>'JR'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'JIRON'],
            ['codigo'=>'ML'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'MALECON'],
            ['codigo'=>'PJE'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'PASAJE'],
            ['codigo'=>'PRLG'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'PROLONGACION'],
            ['codigo'=>'PS'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'PASEO'],
            ['codigo'=>'0'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'RUC'],
            ['codigo'=>'1'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA INDIVIDUAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA COTITULARIDAD'],
            ['codigo'=>'3'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA ACTIVIDAD ECONOMICA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'FCH'	,'desc_codigo'=>'FICHA BIENES COMUNES'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'DIGITADOR(A)'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'SUPERVISOR(A)'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'TÉCNICO(A) CATASTRAL'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'VERIFICADOR(A) CATASTRAL'],
            ['codigo'=>'0'	    ,'id_tabla'=>'TPC'	,'desc_codigo'=>'ADMINISTRADOR'],
            ['codigo'=>'418'	    ,'id_tabla'=>'CDP'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'8'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN ZONA DE RIESGO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO CENTRAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO LOCAL'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO REGIONAL'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'BENEFICENCIA PUBLICA'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'HOSPITALES'],
            ['codigo'=>'6'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ENTIDADES RELIGIOSAS'],
            ['codigo'=>'7'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'CUERPO GENERAL DE BOMBEROS'],
            ['codigo'=>'8'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'UNIVERSIDADES'],
            ['codigo'=>'9'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'CENTRO EDUCATIVO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'COMUNIDAD CAMPESINA / NATIVA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANISMOS INTERNACIONALES'],
            ['codigo'=>'12'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'GOBIERNO EXTRANJERO'],
            ['codigo'=>'13'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANIZACION POLITICA'],
            ['codigo'=>'14'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'PATRIMONIO CULTURAL DE LA NACION'],
            ['codigo'=>'15'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANIZACIONES SINDICALES'],
            ['codigo'=>'16'	    ,'id_tabla'=>'CEF'	,'desc_codigo'=>'ORGANIZACIONES DE DISCAPACITADOS'],
            ['codigo'=>'12'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'PARTIDA DE NACIMIENTO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'DEPARTAMENTO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'CASA / CHALET'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'OFICINA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'ESTACIONAMIENTO'],
            ['codigo'=>'5'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'DEPOSITO'],
            ['codigo'=>'6'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'TENDAL'],
            ['codigo'=>'7'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'TIENDA'],
            ['codigo'=>'16'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'RUT01'	    ,'id_tabla'=>'RUT'	,'desc_codigo'=>'RUTA PLANO PROPIEDADES'],
            ['codigo'=>'OJ'	    ,'id_tabla'=>'VIA'	,'desc_codigo'=>'GGG'],
            ['codigo'=>'8'	    ,'id_tabla'=>'TIF'	,'desc_codigo'=>'AIRES'],
            ['codigo'=>'3'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONSTANCIA DE POSESION'],
            ['codigo'=>'4'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'SUCESION INTESTADA'],
            ['codigo'=>'6'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CLAUSULA DE CANCELACION'],
            ['codigo'=>'7'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'DECLARATORIA DE FÁBRICA'],
            ['codigo'=>'8'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'RECIBO DE LUZ  AGUA Y OTROS SERVICIO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'DCF'	,'desc_codigo'=>'CONTRATO DE ALQUILER'],
            ['codigo'=>'1'	        ,'id_tabla'=>'ECH'	,'desc_codigo'=>'REGISTRADO'],
            ['codigo'=>'2'	        ,'id_tabla'=>'ECH'	,'desc_codigo'=>'REVISADO'],
            ['codigo'=>'10'	    ,'id_tabla'=>'TIN'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'PROPIETARIO UNICO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'SUCESION INTESTADA'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'POSEEDOR'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'SOCIEDAD CONYUGAL'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'COTITULARIDAD'],
            ['codigo'=>'6'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'LITIGIO'],
            ['codigo'=>'7'	    ,'id_tabla'=>'CTF'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'PROPIETARIO UNICO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'SUCESION INTESTADA'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'POSEEDOR'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'SOCIEDAD CONYUGAL'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'COTITULARIDAD'],
            ['codigo'=>'6'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'LITIGIO'],
            ['codigo'=>'7'	    ,'id_tabla'=>'CTT'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CDC'	,'desc_codigo'=>'SIN DATOS'],
            ['codigo'=>'6'	    ,'id_tabla'=>'ECV'	,'desc_codigo'=>'SIN DATOS'],
            ['codigo'=>'4'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'FIERRO'],
            ['codigo'=>'5'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'ROTOPLAS'],
            ['codigo'=>'6'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'POLICARBONATO'],
            ['codigo'=>'7'	    ,'id_tabla'=>'MEP'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'8'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'9'	    ,'id_tabla'=>'DOC'	,'desc_codigo'=>'LIBRETA MILITAR'],
            ['codigo'=>'6'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'GOBIERNO'],
            ['codigo'=>'5'	    ,'id_tabla'=>'TPJ'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'13'	    ,'id_tabla'=>'PEN'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION RESIDENCIAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION COMERCIAL'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION INDUSTRIAL'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION OTROS USOS'],
            ['codigo'=>'5'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION REGLAMENTACION ESPECIAL'],
            ['codigo'=>'6'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION OTROS'],
            ['codigo'=>'7'	    ,'id_tabla'=>'TCZ'	,'desc_codigo'=>'ZONIFICACION EQUIPAMIENTOS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'PATRIMONIO MUNDIAL'],
            ['codigo'=>'2'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'ZONA ARQUEOLOGICA MONUMENTAL'],
            ['codigo'=>'3'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'SITIO ARQUEOLOGICO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'ZONA DE RESERVA ARQUEOLOGICA'],
            ['codigo'=>'5'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'ELEMENTO ARQUEOLOGICO AISLADO'],
            ['codigo'=>'6'	    ,'id_tabla'=>'CDI'	,'desc_codigo'=>'PAISAJE CULTURAL ARQUEOLOGICO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'PRE-CERAMICO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'PERIODO INICIAL'],
            ['codigo'=>'3'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'HORIZONTE TEMPRANO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'INTERMEDIO TEMPRANO'],
            ['codigo'=>'5'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'HORIZONTE MEDIO'],
            ['codigo'=>'6'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'INTERMEDIO TARDIO'],
            ['codigo'=>'7'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'HORIZONTE TARDIO'],
            ['codigo'=>'8'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'VARIOS PERIODOS'],
            ['codigo'=>'9'	    ,'id_tabla'=>'FC'	,'desc_codigo'=>'INDETERMINADO'],
            ['codigo'=>'1'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'CIVIL PUBLICA'],
            ['codigo'=>'2'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'CIVIL DOMESTICA'],
            ['codigo'=>'3'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'RELIGIOSA'],
            ['codigo'=>'4'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'MILITAR'],
            ['codigo'=>'5'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'INDUSTRIAL'],
            ['codigo'=>'6'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'FUNERARIA'],
            ['codigo'=>'7'	    ,'id_tabla'=>'TDA'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'GOTICO'],
            ['codigo'=>'2'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'MUDEJAR'],
            ['codigo'=>'3'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'PLATERESCO'],
            ['codigo'=>'4'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'RENACENTISTA'],
            ['codigo'=>'5'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'MANIERISTA'],
            ['codigo'=>'6'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'BARROCO'],
            ['codigo'=>'7'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ROCOCO'],
            ['codigo'=>'8'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEOCLASICO'],
            ['codigo'=>'9'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEORENACENTISTA'],
            ['codigo'=>'10'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ACADEMICISTA'],
            ['codigo'=>'11'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ART NOUVEAU'],
            ['codigo'=>'12'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEOCOLONIAL'],
            ['codigo'=>'13'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'NEOPERUANO'],
            ['codigo'=>'14'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'INDIGENISTA'],
            ['codigo'=>'15'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'ART DECO'],
            ['codigo'=>'16'	    ,'id_tabla'=>'FE'	,'desc_codigo'=>'OTROS'],
            ['codigo'=>'1'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'AMPLIACION'],
            ['codigo'=>'2'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'ANASTILOSIS'],
            ['codigo'=>'3'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'CONSERVACION'],
            ['codigo'=>'4'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'CONSOLIDACION'],
            ['codigo'=>'5'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'CONSTRUCCION'],
            ['codigo'=>'6'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'DEMOLICION'],
            ['codigo'=>'7'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'RENOVACION URBANA O REVITALIZACION URBANA'],
            ['codigo'=>'8'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'PROTECCION'],
            ['codigo'=>'9'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'PUESTA EN VALOR'],
            ['codigo'=>'10'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'REFACCION'],
            ['codigo'=>'11'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'REMODELACION'],
            ['codigo'=>'12'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'OBRA NUEVA'],
            ['codigo'=>'13'	    ,'id_tabla'=>'IEI'	,'desc_codigo'=>'RESTAURACION'],
            ['codigo'=>'7'	    ,'id_tabla'=>'UCA'	,'desc_codigo'=>'EN BIEN COMUN'],
            ['codigo'=>'4'	    ,'id_tabla'=>'CNP'	,'desc_codigo'=>'SIN NUMERO'],
            ['codigo'=>'7'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'ESCRITURA PUBLICA'],
            ['codigo'=>'8'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'MINUTA COMPRA VENTA'],
            ['codigo'=>'9'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'DOCUMENTO DE TRANSFERENCIA'],
            ['codigo'=>'10'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'CONSTANCIA DE POSESION'],
            ['codigo'=>'11'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'PARTIDA DE DEFUNCION'],
            ['codigo'=>'12'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'CERTIFICADO CATASTRAL'],
            ['codigo'=>'13'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'HOJA INFORMATIVA CATASTRAL'],
            ['codigo'=>'14'	    ,'id_tabla'=>'TDC'	,'desc_codigo'=>'PARTIDA DE NACIMIENTO'],
            ['codigo'=>'C-7'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'C-7 COMERCIO ZONAL'],
            ['codigo'=>'I1-R5'  ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'I1-R5 VIVIENDA TALLER DE ALTA DENSIDAD'],
            ['codigo'=>'E1'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'E1 EDUCACION BASICA'],
            ['codigo'=>'R-5'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'R-5 RESIDENCIAL DE DENSIDAD MEDIA'],
            ['codigo'=>'OU'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'OU OTROS USOS'],
            ['codigo'=>'C-5'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'C-5 COMERCIO ESPECIALIZADO'],
            ['codigo'=>'ZRP1'   ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'ZRP1 ZONA DE RECREACION BARRIAL'],
            ['codigo'=>'E2'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'E2 EDUCACION SUPERIOR TECNOLOGICO'],
            ['codigo'=>'C-3'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'C-3 COMERCIO VECINAL'],
            ['codigo'=>'R-4'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'R-4 RESIDENCIAL DE DENSIDAD MEDIA'],
            ['codigo'=>'H1'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'H1 POSTA MEDICA'],
            ['codigo'=>'ZAM-CH' ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'ZAM-CH AREA DE AMORTIGUAMIENTO'],
            ['codigo'=>'MER'    ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'MERCADO MERCADO'],
            ['codigo'=>'CH'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'CH CENTRO HISTORICO'],
            ['codigo'=>'AP'     ,'id_tabla'=>'ZON'  ,'desc_codigo'=>'AP'],

        ];
        foreach ($tablas as $tabla) {
            TablaCodigo::create($tabla);
        }
    }
}
